insert into solo_drill_library (focus, name, structure, target_intensity, duration_min, equivalent_for) values
('movement', '6-Corner Star Ghosting',
  '{"pattern":"center to each of 6 court corners and back","sets":4,"work_sec":45,"rest_sec":75}'::jsonb, 8, 30, 'oncourt'),
('movement', 'Figure-Eight Rhythm Ghosting',
  '{"pattern":"front-corner to opposite back-corner looping figure-8","sets":5,"work_sec":40,"rest_sec":60}'::jsonb, 7, 25, 'oncourt'),
('movement', 'Front/Back Ghosting Circuit',
  '{"pattern":"short front drop lunge then deep back-corner drive","sets":6,"work_sec":30,"rest_sec":45}'::jsonb, 7, 25, 'oncourt'),
('touch', 'Solo Rail Hitting',
  '{"pattern":"straight-drive rails down both walls, target back third","reps":200,"target":"length past service line"}'::jsonb, 5, 30, 'oncourt'),
('touch', 'Repeated Drops',
  '{"pattern":"soft straight + cross drops off own feed","sets":8,"reps":15}'::jsonb, 4, 25, 'oncourt'),
('touch', 'Boast-and-Drive Combo (solo)',
  '{"pattern":"boast, run to front, straight drive, reset","sets":6,"reps":10}'::jsonb, 6, 30, 'oncourt'),
('fitness', '120-Shot Solo Shadow Drill',
  '{"pattern":"continuous shadow swings across all corners","total_shots":120,"target_time_min":8}'::jsonb, 9, 20, 'oncourt'),
('fitness', 'Court Sprint Intervals',
  '{"pattern":"baseline-to-front-wall sprints","sets":10,"work_sec":15,"rest_sec":45}'::jsonb, 9, 25, 'cardio'),
('mixed', 'Ghost + Hit Pyramid',
  '{"pattern":"alternate 1 min ghosting / 1 min rail hitting, ladder 1-2-3-2-1","rounds":9}'::jsonb, 7, 35, 'oncourt');
